server:
  port: 8003
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: abc123
mybatis:
  # mapper映射文件的路径（resources）,支持直接在resource下的mapper文件夹寻找xml
  mapper-locations: classpath:mapper/*.xml
  # 实体类的包
  type-aliases-package: com.itheima.pojo
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 指定log4j2作为日志记录
logging:
  config: classpath:log4j2-spring.xml
  level:
    root: info
    #这个指定你的dao层，也就是mapper文件的所在包
    com.itheima.mapper: DEBUG

