server:
  port: 18084
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: http://localhost:8848/nacos # nacos地址
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
          filters:
            - AddRequestHeader=truth, huojz is handsom
      defaultFilters:
        - AddRequestHeader=truth, huojz is handsom-defaultFilters
        - PrintAny
        - WithArugs=1,2,3

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
      - /cars