server:
  port: 8081
spring:
  application:
    name: springcloud-service
  profiles:
    active: dev
  # 配置数据源信息
  datasource:
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123
  cloud:
    nacos:
      server-addr: 192.168.124.21:8848 # nacos地址